# Site settings
title: joshbhathal
email: j-bhathal@hotmail.co.uk
description: The Jekyll version of the Highlights theme by HTML5 UP modified by me for me
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://joshbhathal.co.uk/" # the base hostname & protocol for your site
google_analytics: G-5P074CZDZ9 

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url: 
linkedin_url: https://www.linkedin.com/in/josh-bhathal/
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
